#index:
#    path: /
#    controller: App\Controller\DefaultController::index
getAll:
  path: /todo/getAll
  methods: GET
  controller: App\Controller\TodoController::getAll

add:
  path: /todo/add
  methods: POST
  controller: App\Controller\TodoController::add

delete:
  path: /todo/delete
  methods: POST
  controller: App\Controller\TodoController::delete